dist: bionic
language: php
php:
  - 7.4
cache:
  directories:
    - vendor
before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
script:
  - ./vendor/bin/phpcs --standard=ruleset.xml app
  - ./vendor/bin/phpstan analyse -c phpstan.neon app --memory-limit=-1
  - ./vendor/bin/phpunit
