version: '3.5'

networks:
  cdn:
    driver: bridge

services:
  nginx1:
    image: nginx:alpine
    container_name: nginx1
    volumes:
      - ./cdn/html:/var/www/html
      - ./cdn/nginx1:/etc/nginx/conf.d
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=nginx1.localhost
      - NGINX_PORT=80
    networks:
      - cdn
  nginx2:
    image: nginx:alpine
    container_name: nginx2
    volumes:
      - ./cdn/html:/var/www/html
      - ./cdn/nginx2:/etc/nginx/conf.d
    ports:
      - "8082:80"
    environment:
      - NGINX_HOST=nginx2.localhost
      - NGINX_PORT=80
    networks:
      - cdn
  nginx3:
    image: nginx:alpine
    container_name: nginx3
    volumes:
      - ./cdn/html:/var/www/html
      - ./cdn/nginx3:/etc/nginx/conf.d
    ports:
      - "8083:80"
    environment:
      - NGINX_HOST=nginx3.localhost
      - NGINX_PORT=80
    networks:
      - cdn
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./cdn/html:/var/www/html
      - ./cdn/nginx:/etc/nginx/conf.d
      - ./cdn/geo.conf:/etc/nginx/geo.conf
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    links:
      - nginx1
      - nginx2
      - nginx3
    depends_on:
      - nginx1
      - nginx2
      - nginx3
    networks:
      - cdn

