version: '3.5'

networks:
  mysql:
    driver: bridge

services:
  mysql-master:
    build:
      context: ./mysql
    volumes:
      - ./mysql/mysql-master/logs:/var/log/mysql
      - ./mysql/mysql-master/my.cnf:/etc/mysql/my.cnf
      - ./mysql/mysql-master:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - mysql

  mysql-slave-1:
    build:
      context: ./mysql
    volumes:
      - ./mysql/mysql-slave-1/logs:/var/log/mysql
      - ./mysql/mysql-slave-1/my.cnf:/etc/mysql/my.cnf
      - ./mysql/mysql-slave-1:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
    networks:
      - mysql

  mysql-slave-2:
    build:
      context: ./mysql
    volumes:
      - ./mysql/mysql-slave-2/logs:/var/log/mysql
      - ./mysql/mysql-slave-2/my.cnf:/etc/mysql/my.cnf
      - ./mysql/mysql-slave-2:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3308:3306"
    networks:
      - mysql

