version: '3.5'

networks:
  db:
    driver: bridge

services:

  db-main:
    build:
      context: ./postgresql
#    volumes:
#      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - db

  db-shard-1:
    build:
      context: ./postgresql
#    volumes:
#      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=books_1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - db

  db-shard-2:
    build:
      context: ./postgresql
#    volumes:
#      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=books_2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    networks:
      - db

